export type Theme = {
  id: string;
  name: string;
  author?: string;
  colors: {
    background: string;
    foreground: string;
    card: string;
    cardForeground: string;
    popover: string;
    popoverForeground: string;
    primary: string;
    primaryForeground: string;
    secondary: string;
    secondaryForeground: string;
    muted: string;
    mutedForeground: string;
    accent: string;
    accentForeground: string;
    destructive: string;
    destructiveForeground: string;
    border: string;
    input: string;
    ring: string;
  };
  font?: string;
  radius?: number;
};

export const defaultTheme: Theme = {
  id: "dark",
  name: "Dark",
  colors: {
    background: "#1A1A1A",
    foreground: "#FFFFFF",
    card: "#333333",
    cardForeground: "#FFFFFF",
    popover: "#333333",
    popoverForeground: "#FFFFFF",
    primary: "#6200EE",
    primaryForeground: "#FFFFFF",
    secondary: "#333333",
    secondaryForeground: "#FFFFFF",
    muted: "#444444",
    mutedForeground: "#AAAAAA",
    accent: "#6200EE",
    accentForeground: "#FFFFFF",
    destructive: "#FF0000",
    destructiveForeground: "#FFFFFF",
    border: "#444444",
    input: "#444444",
    ring: "#6200EE",
  },
  font: "Inter",
  radius: 8,
};

export const predefinedThemes: Theme[] = [
  defaultTheme,
  {
    id: "light",
    name: "Light",
    colors: {
      background: "#FFFFFF",
      foreground: "#000000",
      card: "#FFFFFF",
      cardForeground: "#000000",
      popover: "#FFFFFF",
      popoverForeground: "#000000",
      primary: "#6200EE",
      primaryForeground: "#FFFFFF",
      secondary: "#F5F5F5",
      secondaryForeground: "#000000",
      muted: "#F5F5F5",
      mutedForeground: "#666666",
      accent: "#6200EE",
      accentForeground: "#FFFFFF",
      destructive: "#FF0000",
      destructiveForeground: "#FFFFFF",
      border: "#E0E0E0",
      input: "#E0E0E0",
      ring: "#6200EE",
    },
    font: "Inter",
    radius: 8,
  },
  {
    id: "dracula",
    name: "Dracula",
    author: "Zeno Rocha",
    colors: {
      background: "#282A36",
      foreground: "#F8F8F2",
      card: "#44475A",
      cardForeground: "#F8F8F2",
      popover: "#44475A",
      popoverForeground: "#F8F8F2",
      primary: "#BD93F9",
      primaryForeground: "#282A36",
      secondary: "#44475A",
      secondaryForeground: "#F8F8F2",
      muted: "#44475A",
      mutedForeground: "#BFBFBF",
      accent: "#FF79C6",
      accentForeground: "#282A36",
      destructive: "#FF5555",
      destructiveForeground: "#F8F8F2",
      border: "#44475A",
      input: "#44475A",
      ring: "#BD93F9",
    },
    font: "Fira Code",
    radius: 4,
  },
  {
    id: "nord",
    name: "Nord",
    author: "Arctic Ice Studio",
    colors: {
      background: "#2E3440",
      foreground: "#ECEFF4",
      card: "#3B4252",
      cardForeground: "#ECEFF4",
      popover: "#3B4252",
      popoverForeground: "#ECEFF4",
      primary: "#88C0D0",
      primaryForeground: "#2E3440",
      secondary: "#3B4252",
      secondaryForeground: "#ECEFF4",
      muted: "#4C566A",
      mutedForeground: "#D8DEE9",
      accent: "#81A1C1",
      accentForeground: "#2E3440",
      destructive: "#BF616A",
      destructiveForeground: "#ECEFF4",
      border: "#4C566A",
      input: "#4C566A",
      ring: "#88C0D0",
    },
    font: "Inter",
    radius: 6,
  },
  {
    id: "github-dark",
    name: "GitHub Dark",
    author: "GitHub",
    colors: {
      background: "#0D1117",
      foreground: "#C9D1D9",
      card: "#161B22",
      cardForeground: "#C9D1D9",
      popover: "#161B22",
      popoverForeground: "#C9D1D9",
      primary: "#58A6FF",
      primaryForeground: "#0D1117",
      secondary: "#161B22",
      secondaryForeground: "#C9D1D9",
      muted: "#21262D",
      mutedForeground: "#8B949E",
      accent: "#58A6FF",
      accentForeground: "#0D1117",
      destructive: "#F85149",
      destructiveForeground: "#C9D1D9",
      border: "#30363D",
      input: "#30363D",
      ring: "#58A6FF",
    },
    font: "Segoe UI",
    radius: 6,
  },
  {
    id: "synthwave",
    name: "Synthwave",
    author: "Bolt",
    colors: {
      background: "#241B2F",
      foreground: "#F8F8F8",
      card: "#2A2139",
      cardForeground: "#F8F8F8",
      popover: "#2A2139",
      popoverForeground: "#F8F8F8",
      primary: "#FF7EDB",
      primaryForeground: "#241B2F",
      secondary: "#2A2139",
      secondaryForeground: "#F8F8F8",
      muted: "#34294F",
      mutedForeground: "#A599E9",
      accent: "#36F9F6",
      accentForeground: "#241B2F",
      destructive: "#FF4A4A",
      destructiveForeground: "#F8F8F8",
      border: "#34294F",
      input: "#34294F",
      ring: "#FF7EDB",
    },
    font: "Outrun Future",
    radius: 10,
  },
  {
    id: "monokai",
    name: "Monokai",
    author: "Wimer Hazenberg",
    colors: {
      background: "#272822",
      foreground: "#F8F8F2",
      card: "#3E3D32",
      cardForeground: "#F8F8F2",
      popover: "#3E3D32",
      popoverForeground: "#F8F8F2",
      primary: "#A6E22E",
      primaryForeground: "#272822",
      secondary: "#3E3D32",
      secondaryForeground: "#F8F8F2",
      muted: "#49483E",
      mutedForeground: "#A59F85",
      accent: "#FD971F",
      accentForeground: "#272822",
      destructive: "#F92672",
      destructiveForeground: "#F8F8F2",
      border: "#49483E",
      input: "#49483E",
      ring: "#A6E22E",
    },
    font: "JetBrains Mono",
    radius: 4,
  },
  {
    id: "solarized-dark",
    name: "Solarized Dark",
    author: "Ethan Schoonover",
    colors: {
      background: "#002B36",
      foreground: "#839496",
      card: "#073642",
      cardForeground: "#839496",
      popover: "#073642",
      popoverForeground: "#839496",
      primary: "#268BD2",
      primaryForeground: "#002B36",
      secondary: "#073642",
      secondaryForeground: "#839496",
      muted: "#073642",
      mutedForeground: "#586E75",
      accent: "#2AA198",
      accentForeground: "#002B36",
      destructive: "#DC322F",
      destructiveForeground: "#839496",
      border: "#073642",
      input: "#073642",
      ring: "#268BD2",
    },
    font: "Inter",
    radius: 4,
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    author: "Enkia",
    colors: {
      background: "#1A1B26",
      foreground: "#A9B1D6",
      card: "#24283B",
      cardForeground: "#A9B1D6",
      popover: "#24283B",
      popoverForeground: "#A9B1D6",
      primary: "#7AA2F7",
      primaryForeground: "#1A1B26",
      secondary: "#24283B",
      secondaryForeground: "#A9B1D6",
      muted: "#24283B",
      mutedForeground: "#565F89",
      accent: "#BB9AF7",
      accentForeground: "#1A1B26",
      destructive: "#F7768E",
      destructiveForeground: "#A9B1D6",
      border: "#24283B",
      input: "#24283B",
      ring: "#7AA2F7",
    },
    font: "JetBrains Mono",
    radius: 6,
  },
  {
    id: "catppuccin-mocha",
    name: "Catppuccin Mocha",
    author: "Catppuccin",
    colors: {
      background: "#1E1E2E",
      foreground: "#CDD6F4",
      card: "#313244",
      cardForeground: "#CDD6F4",
      popover: "#313244",
      popoverForeground: "#CDD6F4",
      primary: "#89B4FA",
      primaryForeground: "#1E1E2E",
      secondary: "#313244",
      secondaryForeground: "#CDD6F4",
      muted: "#313244",
      mutedForeground: "#A6ADC8",
      accent: "#F5C2E7",
      accentForeground: "#1E1E2E",
      destructive: "#F38BA8",
      destructiveForeground: "#CDD6F4",
      border: "#45475A",
      input: "#45475A",
      ring: "#89B4FA",
    },
    font: "Inter",
    radius: 8,
  },
  {
    id: "neon",
    name: "Neon",
    author: "Bolt",
    colors: {
      background: "#000000",
      foreground: "#FFFFFF",
      card: "#0A0A0A",
      cardForeground: "#FFFFFF",
      popover: "#0A0A0A",
      popoverForeground: "#FFFFFF",
      primary: "#00FF00",
      primaryForeground: "#000000",
      secondary: "#0A0A0A",
      secondaryForeground: "#FFFFFF",
      muted: "#1A1A1A",
      mutedForeground: "#AAAAAA",
      accent: "#FF00FF",
      accentForeground: "#000000",
      destructive: "#FF0000",
      destructiveForeground: "#FFFFFF",
      border: "#333333",
      input: "#333333",
      ring: "#00FF00",
    },
    font: "Orbitron",
    radius: 0,
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    author: "Neon",
    colors: {
      background: "#1A1A2E",
      foreground: "#E94560",
      card: "#16213E",
      cardForeground: "#E94560",
      popover: "#16213E",
      popoverForeground: "#E94560",
      primary: "#E94560",
      primaryForeground: "#000000",
      secondary: "#0F3460",
      secondaryForeground: "#E94560",
      muted: "#1A1A2E",
      mutedForeground: "#E94560",
      accent: "#00FFD1",
      accentForeground: "#000000",
      destructive: "#FF0000",
      destructiveForeground: "#FFFFFF",
      border: "#E94560",
      input: "#16213E",
      ring: "#00FFD1",
    },
    font: "Rajdhani",
    radius: 0,
  },
  {
    id: "midnight-ocean",
    name: "Midnight Ocean",
    author: "DeepSea",
    colors: {
      background: "#0A192F",
      foreground: "#CCD6F6",
      card: "#112240",
      cardForeground: "#CCD6F6",
      popover: "#112240",
      popoverForeground: "#CCD6F6",
      primary: "#64FFDA",
      primaryForeground: "#0A192F",
      secondary: "#112240",
      secondaryForeground: "#CCD6F6",
      muted: "#0A192F",
      mutedForeground: "#8892B0",
      accent: "#FF6B6B",
      accentForeground: "#0A192F",
      destructive: "#FF0000",
      destructiveForeground: "#FFFFFF",
      border: "#233554",
      input: "#112240",
      ring: "#64FFDA",
    },
    font: "Poppins",
    radius: 8,
  },
  {
    id: "sunset-glow",
    name: "Sunset Glow",
    author: "Horizon",
    colors: {
      background: "#2C3E50",
      foreground: "#ECF0F1",
      card: "#34495E",
      cardForeground: "#ECF0F1",
      popover: "#34495E",
      popoverForeground: "#ECF0F1",
      primary: "#E67E22",
      primaryForeground: "#2C3E50",
      secondary: "#34495E",
      secondaryForeground: "#ECF0F1",
      muted: "#2C3E50",
      mutedForeground: "#BDC3C7",
      accent: "#9B59B6",
      accentForeground: "#2C3E50",
      destructive: "#E74C3C",
      destructiveForeground: "#FFFFFF",
      border: "#34495E",
      input: "#34495E",
      ring: "#E67E22",
    },
    font: "Lato",
    radius: 6,
  },
  {
    id: "forest-mist",
    name: "Forest Mist",
    author: "Greenwood",
    colors: {
      background: "#1E3A2F",
      foreground: "#D4ECDD",
      card: "#2A4A3C",
      cardForeground: "#D4ECDD",
      popover: "#2A4A3C",
      popoverForeground: "#D4ECDD",
      primary: "#4CAF50",
      primaryForeground: "#1E3A2F",
      secondary: "#2A4A3C",
      secondaryForeground: "#D4ECDD",
      muted: "#1E3A2F",
      mutedForeground: "#A3C1AD",
      accent: "#FFC107",
      accentForeground: "#1E3A2F",
      destructive: "#FF5252",
      destructiveForeground: "#FFFFFF",
      border: "#2A4A3C",
      input: "#2A4A3C",
      ring: "#4CAF50",
    },
    font: "Merriweather",
    radius: 12,
  },
  {
    id: "arctic-frost",
    name: "Arctic Frost",
    author: "Frostbite",
    colors: {
      background: "#E3F2FD",
      foreground: "#0D47A1",
      card: "#BBDEFB",
      cardForeground: "#0D47A1",
      popover: "#BBDEFB",
      popoverForeground: "#0D47A1",
      primary: "#2196F3",
      primaryForeground: "#E3F2FD",
      secondary: "#BBDEFB",
      secondaryForeground: "#0D47A1",
      muted: "#E3F2FD",
      mutedForeground: "#64B5F6",
      accent: "#FF4081",
      accentForeground: "#0D47A1",
      destructive: "#FF1744",
      destructiveForeground: "#FFFFFF",
      border: "#90CAF9",
      input: "#BBDEFB",
      ring: "#2196F3",
    },
    font: "Roboto",
    radius: 10,
  },
  {
    id: "crimson-night",
    name: "Crimson Night",
    author: "Bloodmoon",
    colors: {
      background: "#1A1A1A",
      foreground: "#FF5252",
      card: "#2A2A2A",
      cardForeground: "#FF5252",
      popover: "#2A2A2A",
      popoverForeground: "#FF5252",
      primary: "#FF5252",
      primaryForeground: "#1A1A1A",
      secondary: "#2A2A2A",
      secondaryForeground: "#FF5252",
      muted: "#1A1A1A",
      mutedForeground: "#FF8A80",
      accent: "#FF4081",
      accentForeground: "#1A1A1A",
      destructive: "#D32F2F",
      destructiveForeground: "#FFFFFF",
      border: "#2A2A2A",
      input: "#2A2A2A",
      ring: "#FF5252",
    },
    font: "Oswald",
    radius: 0,
  },
  {
    id: "golden-hour",
    name: "Golden Hour",
    author: "Sunset",
    colors: {
      background: "#FFD700",
      foreground: "#8B4513",
      card: "#FFC107",
      cardForeground: "#8B4513",
      popover: "#FFC107",
      popoverForeground: "#8B4513",
      primary: "#8B4513",
      primaryForeground: "#FFD700",
      secondary: "#FFC107",
      secondaryForeground: "#8B4513",
      muted: "#FFD700",
      mutedForeground: "#A1887F",
      accent: "#FF5722",
      accentForeground: "#8B4513",
      destructive: "#D32F2F",
      destructiveForeground: "#FFFFFF",
      border: "#FFC107",
      input: "#FFC107",
      ring: "#8B4513",
    },
    font: "Playfair Display",
    radius: 8,
  },
  {
    id: "pastel-dreams",
    name: "Pastel Dreams",
    author: "CottonCandy",
    colors: {
      background: "#F8BBD0",
      foreground: "#880E4F",
      card: "#F48FB1",
      cardForeground: "#880E4F",
      popover: "#F48FB1",
      popoverForeground: "#880E4F",
      primary: "#880E4F",
      primaryForeground: "#F8BBD0",
      secondary: "#F48FB1",
      secondaryForeground: "#880E4F",
      muted: "#F8BBD0",
      mutedForeground: "#C2185B",
      accent: "#FF80AB",
      accentForeground: "#880E4F",
      destructive: "#D50000",
      destructiveForeground: "#FFFFFF",
      border: "#F48FB1",
      input: "#F48FB1",
      ring: "#880E4F",
    },
    font: "Comic Sans MS",
    radius: 12,
  },
  {
    id: "galactic-void",
    name: "Galactic Void",
    author: "Astro",
    colors: {
      background: "#000033",
      foreground: "#FFFFFF",
      card: "#000044",
      cardForeground: "#FFFFFF",
      popover: "#000044",
      popoverForeground: "#FFFFFF",
      primary: "#00FFFF",
      primaryForeground: "#000033",
      secondary: "#000044",
      secondaryForeground: "#FFFFFF",
      muted: "#000033",
      mutedForeground: "#9999FF",
      accent: "#FF00FF",
      accentForeground: "#000033",
      destructive: "#FF0000",
      destructiveForeground: "#FFFFFF",
      border: "#000044",
      input: "#000044",
      ring: "#00FFFF",
    },
    font: "Orbitron",
    radius: 0,
  },
  {
    id: "neon-pulse",
    name: "Neon Pulse",
    author: "Hemant",
    colors: {
      background: "#0A0A0A",
      foreground: "#FF00FF",
      card: "#1A1A1A",
      cardForeground: "#FF00FF",
      popover: "#1A1A1A",
      popoverForeground: "#FF00FF",
      primary: "#00FF00",
      primaryForeground: "#0A0A0A",
      secondary: "#1A1A1A",
      secondaryForeground: "#FF00FF",
      muted: "#0A0A0A",
      mutedForeground: "#FF66FF",
      accent: "#00FFFF",
      accentForeground: "#0A0A0A",
      destructive: "#FF0000",
      destructiveForeground: "#FFFFFF",
      border: "#333333",
      input: "#1A1A1A",
      ring: "#00FF00",
    },
    font: "Orbitron",
    radius: 0,
  },
  {
    id: "mystic-aurora",
    name: "Mystic Aurora",
    author: "Hemant",
    colors: {
      background: "#0B0F1A",
      foreground: "#A6E3E9",
      card: "#1A1F2E",
      cardForeground: "#A6E3E9",
      popover: "#1A1F2E",
      popoverForeground: "#A6E3E9",
      primary: "#71C6E9",
      primaryForeground: "#0B0F1A",
      secondary: "#1A1F2E",
      secondaryForeground: "#A6E3E9",
      muted: "#0B0F1A",
      mutedForeground: "#71C6E9",
      accent: "#FF6F61",
      accentForeground: "#0B0F1A",
      destructive: "#FF3B30",
      destructiveForeground: "#FFFFFF",
      border: "#2A2F3D",
      input: "#1A1F2E",
      ring: "#71C6E9",
    },
    font: "Nunito",
    radius: 8,
  },
  {
    id: "royal-velvet",
    name: "Royal Velvet",
    author: "Hemant",
    colors: {
      background: "#1E1A2F",
      foreground: "#D4AF37",
      card: "#2A2440",
      cardForeground: "#D4AF37",
      popover: "#2A2440",
      popoverForeground: "#D4AF37",
      primary: "#9B59B6",
      primaryForeground: "#1E1A2F",
      secondary: "#2A2440",
      secondaryForeground: "#D4AF37",
      muted: "#1E1A2F",
      mutedForeground: "#A98BB6",
      accent: "#FFD700",
      accentForeground: "#1E1A2F",
      destructive: "#FF0000",
      destructiveForeground: "#FFFFFF",
      border: "#3A3450",
      input: "#2A2440",
      ring: "#9B59B6",
    },
    font: "Cinzel",
    radius: 6,
  },
  {
    id: "ocean-breeze",
    name: "Ocean Breeze",
    author: "Hemant",
    colors: {
      background: "#E0F7FA",
      foreground: "#00796B",
      card: "#B2EBF2",
      cardForeground: "#00796B",
      popover: "#B2EBF2",
      popoverForeground: "#00796B",
      primary: "#00BCD4",
      primaryForeground: "#E0F7FA",
      secondary: "#B2EBF2",
      secondaryForeground: "#00796B",
      muted: "#E0F7FA",
      mutedForeground: "#0097A7",
      accent: "#FF6F00",
      accentForeground: "#00796B",
      destructive: "#D32F2F",
      destructiveForeground: "#FFFFFF",
      border: "#80DEEA",
      input: "#B2EBF2",
      ring: "#00BCD4",
    },
    font: "Quicksand",
    radius: 12,
  },
  {
    id: "cyber-neon",
    name: "Cyber Neon",
    author: "Hemant",
    colors: {
      background: "#000000",
      foreground: "#00FFCC",
      card: "#0A0A0A",
      cardForeground: "#00FFCC",
      popover: "#0A0A0A",
      popoverForeground: "#00FFCC",
      primary: "#00FFCC",
      primaryForeground: "#000000",
      secondary: "#0A0A0A",
      secondaryForeground: "#00FFCC",
      muted: "#000000",
      mutedForeground: "#00CC99",
      accent: "#FF00FF",
      accentForeground: "#000000",
      destructive: "#FF0000",
      destructiveForeground: "#FFFFFF",
      border: "#333333",
      input: "#0A0A0A",
      ring: "#00FFCC",
    },
    font: "Rajdhani",
    radius: 0,
  },
  {
    id: "sunset-mirage",
    name: "Sunset Mirage",
    author: "Hemant",
    colors: {
      background: "#2C3E50",
      foreground: "#F39C12",
      card: "#34495E",
      cardForeground: "#F39C12",
      popover: "#34495E",
      popoverForeground: "#F39C12",
      primary: "#E67E22",
      primaryForeground: "#2C3E50",
      secondary: "#34495E",
      secondaryForeground: "#F39C12",
      muted: "#2C3E50",
      mutedForeground: "#E67E22",
      accent: "#9B59B6",
      accentForeground: "#2C3E50",
      destructive: "#E74C3C",
      destructiveForeground: "#FFFFFF",
      border: "#34495E",
      input: "#34495E",
      ring: "#E67E22",
    },
    font: "Lato",
    radius: 8,
  },
  {
    id: "frosted-glass",
    name: "Frosted Glass",
    author: "Hemant",
    colors: {
      background: "#F0F4F8",
      foreground: "#3C4858",
      card: "#FFFFFF",
      cardForeground: "#3C4858",
      popover: "#FFFFFF",
      popoverForeground: "#3C4858",
      primary: "#1E90FF",
      primaryForeground: "#F0F4F8",
      secondary: "#FFFFFF",
      secondaryForeground: "#3C4858",
      muted: "#F0F4F8",
      mutedForeground: "#8392A5",
      accent: "#FF6B6B",
      accentForeground: "#3C4858",
      destructive: "#FF3B30",
      destructiveForeground: "#FFFFFF",
      border: "#E0E6ED",
      input: "#FFFFFF",
      ring: "#1E90FF",
    },
    font: "Inter",
    radius: 12,
  },
  {
    id: "candy-crush",
    name: "Candy Crush",
    author: "Hemant",
    colors: {
      background: "#FFCCCC",
      foreground: "#FF0066",
      card: "#FF99CC",
      cardForeground: "#FF0066",
      popover: "#FF99CC",
      popoverForeground: "#FF0066",
      primary: "#FF0066",
      primaryForeground: "#FFCCCC",
      secondary: "#FF99CC",
      secondaryForeground: "#FF0066",
      muted: "#FFCCCC",
      mutedForeground: "#FF6699",
      accent: "#FF9900",
      accentForeground: "#FF0066",
      destructive: "#FF0000",
      destructiveForeground: "#FFFFFF",
      border: "#FF99CC",
      input: "#FF99CC",
      ring: "#FF0066",
    },
    font: "Comic Sans MS",
    radius: 16,
  },
  {
    id: "midnight-galaxy",
    name: "Midnight Galaxy",
    author: "Hemant",
    colors: {
      background: "#0A0A1A",
      foreground: "#AAB8C2",
      card: "#1A1A2E",
      cardForeground: "#AAB8C2",
      popover: "#1A1A2E",
      popoverForeground: "#AAB8C2",
      primary: "#6C5CE7",
      primaryForeground: "#0A0A1A",
      secondary: "#1A1A2E",
      secondaryForeground: "#AAB8C2",
      muted: "#0A0A1A",
      mutedForeground: "#6C5CE7",
      accent: "#FF7675",
      accentForeground: "#0A0A1A",
      destructive: "#FF3B30",
      destructiveForeground: "#FFFFFF",
      border: "#2A2A40",
      input: "#1A1A2E",
      ring: "#6C5CE7",
    },
    font: "Space Mono",
    radius: 4,
  },
  {
    id: "golden-sands",
    name: "Golden Sands",
    author: "Hemant",
    colors: {
      background: "#FFF8E1",
      foreground: "#FF8F00",
      card: "#FFECB3",
      cardForeground: "#FF8F00",
      popover: "#FFECB3",
      popoverForeground: "#FF8F00",
      primary: "#FF8F00",
      primaryForeground: "#FFF8E1",
      secondary: "#FFECB3",
      secondaryForeground: "#FF8F00",
      muted: "#FFF8E1",
      mutedForeground: "#FFB74D",
      accent: "#FF6F00",
      accentForeground: "#FF8F00",
      destructive: "#D32F2F",
      destructiveForeground: "#FFFFFF",
      border: "#FFD54F",
      input: "#FFECB3",
      ring: "#FF8F00",
    },
    font: "Playfair Display",
    radius: 8,
  },
  {
    id: "obsidian-royal",
    name: "Obsidian Royal",
    author: "Hemant",
    colors: {
      background: "#0A0A0A",
      foreground: "#D4AF37",
      card: "#1A1A1A",
      cardForeground: "#D4AF37",
      popover: "#1A1A1A",
      popoverForeground: "#D4AF37",
      primary: "#D4AF37",
      primaryForeground: "#0A0A0A",
      secondary: "#1A1A1A",
      secondaryForeground: "#D4AF37",
      muted: "#0A0A0A",
      mutedForeground: "#A98F5E",
      accent: "#9B59B6",
      accentForeground: "#0A0A0A",
      destructive: "#D32F2F",
      destructiveForeground: "#FFFFFF",
      border: "#333333",
      input: "#1A1A1A",
      ring: "#D4AF37",
    },
    font: "Cinzel",
    radius: 6,
  },
  {
    id: "midnight-sapphire",
    name: "Midnight Sapphire",
    author: "Hemant",
    colors: {
      background: "#0A1A2A",
      foreground: "#4A90E2",
      card: "#1A2A3A",
      cardForeground: "#4A90E2",
      popover: "#1A2A3A",
      popoverForeground: "#4A90E2",
      primary: "#4A90E2",
      primaryForeground: "#0A1A2A",
      secondary: "#1A2A3A",
      secondaryForeground: "#4A90E2",
      muted: "#0A1A2A",
      mutedForeground: "#6C8EBF",
      accent: "#FF6F61",
      accentForeground: "#0A1A2A",
      destructive: "#FF3B30",
      destructiveForeground: "#FFFFFF",
      border: "#2A3A4A",
      input: "#1A2A3A",
      ring: "#4A90E2",
    },
    font: "Merriweather",
    radius: 8,
  },
  {
    id: "velvet-noir",
    name: "Velvet Noir",
    author: "Hemant",
    colors: {
      background: "#1A1A1A",
      foreground: "#E0B0FF",
      card: "#2A2A2A",
      cardForeground: "#E0B0FF",
      popover: "#2A2A2A",
      popoverForeground: "#E0B0FF",
      primary: "#E0B0FF",
      primaryForeground: "#1A1A1A",
      secondary: "#2A2A2A",
      secondaryForeground: "#E0B0FF",
      muted: "#1A1A1A",
      mutedForeground: "#A98BB6",
      accent: "#FF6F61",
      accentForeground: "#1A1A1A",
      destructive: "#D32F2F",
      destructiveForeground: "#FFFFFF",
      border: "#3A3A3A",
      input: "#2A2A2A",
      ring: "#E0B0FF",
    },
    font: "Playfair Display",
    radius: 8,
  },
  {
    id: "crimson-dynasty",
    name: "Crimson Dynasty",
    author: "Hemant",
    colors: {
      background: "#1A0A0A",
      foreground: "#D32F2F",
      card: "#2A1A1A",
      cardForeground: "#D32F2F",
      popover: "#2A1A1A",
      popoverForeground: "#D32F2F",
      primary: "#D32F2F",
      primaryForeground: "#1A0A0A",
      secondary: "#2A1A1A",
      secondaryForeground: "#D32F2F",
      muted: "#1A0A0A",
      mutedForeground: "#A82A2A",
      accent: "#FF6F61",
      accentForeground: "#1A0A0A",
      destructive: "#FF0000",
      destructiveForeground: "#FFFFFF",
      border: "#3A2A2A",
      input: "#2A1A1A",
      ring: "#D32F2F",
    },
    font: "Oswald",
    radius: 6,
  },
  {
    id: "emerald-majesty",
    name: "Emerald Majesty",
    author: "Hemant",
    colors: {
      background: "#0A1A0A",
      foreground: "#2ECC71",
      card: "#1A2A1A",
      cardForeground: "#2ECC71",
      popover: "#1A2A1A",
      popoverForeground: "#2ECC71",
      primary: "#2ECC71",
      primaryForeground: "#0A1A0A",
      secondary: "#1A2A1A",
      secondaryForeground: "#2ECC71",
      muted: "#0A1A0A",
      mutedForeground: "#1E8449",
      accent: "#FF6F61",
      accentForeground: "#0A1A0A",
      destructive: "#D32F2F",
      destructiveForeground: "#FFFFFF",
      border: "#2A3A2A",
      input: "#1A2A1A",
      ring: "#2ECC71",
    },
    font: "Raleway",
    radius: 8,
  },
  {
    id: "royal-amethyst",
    name: "Royal Amethyst",
    author: "Hemant",
    colors: {
      background: "#1A0A1A",
      foreground: "#9B59B6",
      card: "#2A1A2A",
      cardForeground: "#9B59B6",
      popover: "#2A1A2A",
      popoverForeground: "#9B59B6",
      primary: "#9B59B6",
      primaryForeground: "#1A0A1A",
      secondary: "#2A1A2A",
      secondaryForeground: "#9B59B6",
      muted: "#1A0A1A",
      mutedForeground: "#6C4180",
      accent: "#FF6F61",
      accentForeground: "#1A0A1A",
      destructive: "#D32F2F",
      destructiveForeground: "#FFFFFF",
      border: "#3A2A3A",
      input: "#2A1A2A",
      ring: "#9B59B6",
    },
    font: "Cinzel",
    radius: 6,
  },
  {
    id: "shadow-monarch",
    name: "Shadow Monarch",
    author: "Hemant",
    colors: {
      background: "#0A0A0A",
      foreground: "#AAB8C2",
      card: "#1A1A1A",
      cardForeground: "#AAB8C2",
      popover: "#1A1A1A",
      popoverForeground: "#AAB8C2",
      primary: "#AAB8C2",
      primaryForeground: "#0A0A0A",
      secondary: "#1A1A1A",
      secondaryForeground: "#AAB8C2",
      muted: "#0A0A0A",
      mutedForeground: "#6C7A8C",
      accent: "#FF6F61",
      accentForeground: "#0A0A0A",
      destructive: "#D32F2F",
      destructiveForeground: "#FFFFFF",
      border: "#2A2A2A",
      input: "#1A1A1A",
      ring: "#AAB8C2",
    },
    font: "Lora",
    radius: 8,
  },
  {
    id: "golden-obsidian",
    name: "Golden Obsidian",
    author: "Hemant",
    colors: {
      background: "#0A0A0A",
      foreground: "#FFD700",
      card: "#1A1A1A",
      cardForeground: "#FFD700",
      popover: "#1A1A1A",
      popoverForeground: "#FFD700",
      primary: "#FFD700",
      primaryForeground: "#0A0A0A",
      secondary: "#1A1A1A",
      secondaryForeground: "#FFD700",
      muted: "#0A0A0A",
      mutedForeground: "#B8860B",
      accent: "#FF6F61",
      accentForeground: "#0A0A0A",
      destructive: "#D32F2F",
      destructiveForeground: "#FFFFFF",
      border: "#2A2A2A",
      input: "#1A1A1A",
      ring: "#FFD700",
    },
    font: "Playfair Display",
    radius: 6,
  },
  {
    id: "platinum-eclipse",
    name: "Platinum Eclipse",
    author: "Hemant",
    colors: {
      background: "#1A1A1A",
      foreground: "#E5E4E2",
      card: "#2A2A2A",
      cardForeground: "#E5E4E2",
      popover: "#2A2A2A",
      popoverForeground: "#E5E4E2",
      primary: "#E5E4E2",
      primaryForeground: "#1A1A1A",
      secondary: "#2A2A2A",
      secondaryForeground: "#E5E4E2",
      muted: "#1A1A1A",
      mutedForeground: "#A6A6A6",
      accent: "#FF6F61",
      accentForeground: "#1A1A1A",
      destructive: "#D32F2F",
      destructiveForeground: "#FFFFFF",
      border: "#3A3A3A",
      input: "#2A2A2A",
      ring: "#E5E4E2",
    },
    font: "Roboto Slab",
    radius: 8,
  },
  {
    id: "regal-onyx",
    name: "Regal Onyx",
    author: "Hemant",
    colors: {
      background: "#0A0A0A",
      foreground: "#FFFFFF",
      card: "#1A1A1A",
      cardForeground: "#FFFFFF",
      popover: "#1A1A1A",
      popoverForeground: "#FFFFFF",
      primary: "#FFFFFF",
      primaryForeground: "#0A0A0A",
      secondary: "#1A1A1A",
      secondaryForeground: "#FFFFFF",
      muted: "#0A0A0A",
      mutedForeground: "#A6A6A6",
      accent: "#FF6F61",
      accentForeground: "#0A0A0A",
      destructive: "#D32F2F",
      destructiveForeground: "#FFFFFF",
      border: "#2A2A2A",
      input: "#1A1A1A",
      ring: "#FFFFFF",
    },
    font: "Cinzel",
    radius: 6,
  },
  {
    id: "crimson-shadow",
    name: "Crimson Shadow",
    author: "Hemant",
    colors: {
      background: "#121212",
      foreground: "#FF4444",
      card: "#1E1E1E",
      cardForeground: "#FF4444",
      popover: "#1E1E1E",
      popoverForeground: "#FF4444",
      primary: "#FF4444",
      primaryForeground: "#121212",
      secondary: "#1E1E1E",
      secondaryForeground: "#FF4444",
      muted: "#121212",
      mutedForeground: "#FF7777",
      accent: "#FF6F61",
      accentForeground: "#121212",
      destructive: "#D32F2F",
      destructiveForeground: "#FFFFFF",
      border: "#2A2A2A",
      input: "#1E1E1E",
      ring: "#FF4444",
    },
    font: "Montserrat",
    radius: 8,
  },
  {
    id: "scarlet-night",
    name: "Scarlet Night",
    author: "Hemant",
    colors: {
      background: "#1A1A1A",
      foreground: "#FFFFFF",
      card: "#262626",
      cardForeground: "#FFFFFF",
      popover: "#262626",
      popoverForeground: "#FFFFFF",
      primary: "#FF4444",
      primaryForeground: "#1A1A1A",
      secondary: "#262626",
      secondaryForeground: "#FFFFFF",
      muted: "#1A1A1A",
      mutedForeground: "#A6A6A6",
      accent: "#FF4444",
      accentForeground: "#1A1A1A",
      destructive: "#D32F2F",
      destructiveForeground: "#FFFFFF",
      border: "#333333",
      input: "#262626",
      ring: "#FF4444",
    },
    font: "Roboto",
    radius: 8,
  },
  {
    id: "alien-abduction",
    name: "Alien Abduction",
    author: "Hemant",
    colors: {
      background: "#0A0A0A",
      foreground: "#00FFA2",
      card: "#1A1A1A",
      cardForeground: "#FF00A2",
      popover: "#1A1A1A",
      popoverForeground: "#FF00A2",
      primary: "#00FFA2",
      primaryForeground: "#0A0A0A",
      secondary: "#1A1A1A",
      secondaryForeground: "#FF00A2",
      muted: "#0A0A0A",
      mutedForeground: "#00FFA2",
      accent: "#FF00A2",
      accentForeground: "#0A0A0A",
      destructive: "#FF0000",
      destructiveForeground: "#FFFFFF",
      border: "#00FFA2",
      input: "#1A1A1A",
      ring: "#FF00A2",
    },
    font: "Orbitron",
    radius: 12,
  },
  {
    id: "garbage-day",
    name: "Garbage Day",
    author: "Hemant",
    colors: {
      background: "#4A4A4A",
      foreground: "#FFD700",
      card: "#666666",
      cardForeground: "#FFD700",
      popover: "#666666",
      popoverForeground: "#FFD700",
      primary: "#FFD700",
      primaryForeground: "#4A4A4A",
      secondary: "#666666",
      secondaryForeground: "#FFD700",
      muted: "#4A4A4A",
      mutedForeground: "#FFD700",
      accent: "#FF6F61",
      accentForeground: "#4A4A4A",
      destructive: "#FF0000",
      destructiveForeground: "#FFFFFF",
      border: "#FFD700",
      input: "#666666",
      ring: "#FF6F61",
    },
    font: "Impact",
    radius: 4,
  }
];

export const fontOptions = [
  "Inter",
  "Roboto",
  "Poppins",
  "JetBrains Mono",
  "Fira Code",
  "Segoe UI",
  "Orbitron",
  "Outrun Future",
  "System UI",
  "Arial",
  "Helvetica",
  "Times New Roman",
  "Georgia",
  "Verdana",
  "Courier New",
  "Ink Free",
];

export function hexToHsl(hex: string): [number, number, number] {
  hex = hex.replace(/^#/, '');
  
  let r = parseInt(hex.slice(0, 2), 16) / 255;
  let g = parseInt(hex.slice(2, 4), 16) / 255;
  let b = parseInt(hex.slice(4, 6), 16) / 255;
  
  // Find the min and max values to calculate the lightness
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  
  // Calculate the lightness
  let h = 0;
  let s = 0;
  let l = (max + min) / 2;
  
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    
    switch (max) {
      case r:
        h = (g - b) / d + (g < b ? 6 : 0);
        break;
      case g:
        h = (b - r) / d + 2;
        break;
      case b:
        h = (r - g) / d + 4;
        break;
    }
    
    h /= 6;
  }
  
  // Convert to degrees, percentage, percentage
  return [Math.round(h * 360), Math.round(s * 100), Math.round(l * 100)];
}

export function themeToHsl(theme: Theme): Record<string, string> {
  const hslColors: Record<string, string> = {};
  
  Object.entries(theme.colors).forEach(([key, value]) => {
    const [h, s, l] = hexToHsl(value);
    hslColors[key] = `${h} ${s}% ${l}%`;
  });
  
  return hslColors;
}

export function applyTheme(theme: Theme): void {
  const root = document.documentElement;
  const hslColors = themeToHsl(theme);
  
  Object.entries(hslColors).forEach(([key, value]) => {
    const cssKey = key.replace(/([A-Z])/g, '-$1').toLowerCase();
    root.style.setProperty(`--${cssKey}`, value);
  });
  
  // Apply radius
  if (theme.radius !== undefined) {
    root.style.setProperty('--radius', `${theme.radius}px`);
  }
  
  if (theme.font) {
    root.style.setProperty('--font-family', theme.font);
    document.body.style.fontFamily = `var(--font-family), sans-serif`;
  }
}